# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52200ee10d660b62b4b0893b23c1bf93a92c5c8959f764131a9af60cfaf7a39f1b5a966b4019d3684c4a03152ce8010dc1e5cbc6152a032be0e38f31c27bb627

test:
  secret_key_base: a00bddf778f4043364d72a4daf6c3ab2f504c0077a656f48f6ee2d9cd95a9d3e00159298d5ec125c767f3a616c8d25b40fd10079c266d4a9ad974ca6b35cb201

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
